SHELL := /bin/bash

.PHONY: test-go build-go

test-go:
	cd agent && go test ./...
	cd sidecar && go test ./...
	cd hub/collector-engine && go test ./...
	cd hub/log-pipeline && go test ./...
	cd hub/alert-engine && go test ./...
	cd hub/api-server && go test ./...

build-go:
	cd agent && go build ./...
	cd sidecar && go build ./...
	cd hub/collector-engine && go build ./...
	cd hub/log-pipeline && go build ./...
	cd hub/alert-engine && go build ./...
	cd hub/api-server && go build ./...

